/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package timerapplication;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoUnit;
import java.time.temporal.Temporal;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author HP
 */
public class NewJFrame extends javax.swing.JFrame {

    private Temporal LocalTime() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public class Sekunde{
    long sek =0;
    
    public long getSek(){
        return sek;
    }
    public void setSek(long sek){
        this.sek=sek;
    }
    }
    
    static boolean blic = true;
    BackgroundChange bc = new BackgroundChange();
    Sekunde s = new Sekunde();
    Timer tm;
    
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        onTimeButton = new javax.swing.JRadioButton();
        countdownButton = new javax.swing.JRadioButton();
        onTimeText = new javax.swing.JTextField();
        countdownText = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        startButton = new javax.swing.JButton();
        stopButton = new javax.swing.JButton();
        bojaTexta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        onTimeButton.setText("on time:");
        onTimeButton.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                onTimeButtonStateChanged(evt);
            }
        });

        countdownButton.setText("countdown(mins)");
        countdownButton.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                countdownButtonStateChanged(evt);
            }
        });

        onTimeText.setText("jTextField1");

        countdownText.setText("jTextField2");

        jButton1.setText("Choose color");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jLabel1.setText("Speed:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " 1", " 2", " 3", " 4" }));

        startButton.setText("Start");
        startButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startButtonMouseClicked(evt);
            }
        });
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        stopButton.setText("Stop");
        stopButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stopButtonMouseClicked(evt);
            }
        });

        bojaTexta.setText("bojaTexta");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(countdownButton)
                                    .addComponent(onTimeButton)
                                    .addComponent(jButton1)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(startButton)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(stopButton)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(countdownText, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                        .addComponent(onTimeText))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(bojaTexta)))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(onTimeButton)
                    .addComponent(onTimeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(countdownButton)
                    .addComponent(countdownText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(bojaTexta))
                .addGap(53, 53, 53)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startButton)
                    .addComponent(stopButton))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startButtonActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
Color c = JColorChooser.showDialog(null, "Choose color", Color.yellow);
bojaTexta.setForeground(c);
bojaTexta.setText("Color selected");
    }//GEN-LAST:event_jButton1MouseClicked

    private void stopButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stopButtonMouseClicked
jButton1.setEnabled(true);
jComboBox1.setEnabled(true);
startButton.setEnabled(true);
countdownButton.setEnabled(true);
onTimeButton.setEnabled(true);
onTimeText.setEditable(true);
countdownText.setEditable(true);
onTimeText.setText("");
countdownText.setText("");
bc.dispose();
tm.stop();
    }//GEN-LAST:event_stopButtonMouseClicked

    private void startButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startButtonMouseClicked
jButton1.setEnabled(false);
jComboBox1.setEnabled(false);
startButton.setEnabled(false);
countdownButton.setEnabled(false);
onTimeButton.setEnabled(false);
onTimeText.setEditable(false);
countdownText.setEditable(false);

if(countdownButton.isSelected())
{
    try
    {
        s.setSek((long) (Integer.parseInt(countdownText.getText())) *1000 -1000);
    }
    catch(NumberFormatException exc){
        JOptionPane.showMessageDialog(null, "Morate unijeti broj sekundi");
    }
}
else if(onTimeButton.isSelected())
{
    String onTime = onTimeText.getText();
    if(onTime.trim() =="")
    {
        JOptionPane.showMessageDialog(null, "");
    }
    else
    {
        DateTimeFormatter sdt = DateTimeFormatter.ofPattern("HH:mm:ss");
        LocalTime vrijeme;
        try{
            vrijeme = LocalTime.parse(onTime,sdt);
            s.setSek(Math.abs(ChronoUnit.SECONDS.between(vrijeme, LocalTime())) *1000);
        }
        catch (Exception ex){
            JOptionPane.showMessageDialog(null, "Morate unijeti vrijeme");
        }
    }
}



tm = new Timer(((jComboBox1.getSelectedIndex() + 1) *1000),(ActionEvent e) ->{
    long sekund = s.getSek();
    if(sekund >= 0)
    {
        s.setSek(sekund - 1000);
        if(countdownButton.isSelected())
            countdownText.setText(sekund/1000+"");
    }
    else{
        bc.setVisible(true);
        if (blic == true){
            bc.getContentPane().setBackground(bojaTexta.getForeground());
            bc.repaint();
            blic = false ;
        }
        else
        {
            bc.getContentPane().setBackground(Color.WHITE);
            bc.repaint();
            blic = true;
        }
    }
});
tm.start();


    }//GEN-LAST:event_startButtonMouseClicked

    private void onTimeButtonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_onTimeButtonStateChanged
if(onTimeButton.isSelected())
    onTimeText.setEditable(true);
else
    onTimeText.setEditable(false);
    }//GEN-LAST:event_onTimeButtonStateChanged

    private void countdownButtonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_countdownButtonStateChanged
if(countdownButton.isSelected())
    countdownText.setEditable(true);
else
    countdownText.setEditable(false);
    }//GEN-LAST:event_countdownButtonStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bojaTexta;
    private javax.swing.JRadioButton countdownButton;
    private javax.swing.JTextField countdownText;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton onTimeButton;
    private javax.swing.JTextField onTimeText;
    private javax.swing.JButton startButton;
    private javax.swing.JButton stopButton;
    // End of variables declaration//GEN-END:variables
}
